### PR TITLE
Create Readme.md

### PR DESCRIPTION
**Pull request by ItsK1tty**

### CODE REVIEW

**Review by ItsK1tty — COMMENTED** [review]
grammatical mistakes fix

**Comment by dextonanderson** [comment]
cinemadisplays doesn't use MCEF. This is a project specifically for https://stevecinema.com

**Comment by dextonanderson** [comment]
Oh, sorry, misread

**Comment by ItsK1tty** [comment]
I mentioned JCEF

**Comment by dextonanderson** [comment]
I think I'd like to write a README better describing how this is used. It's fairly specific to our project at Steve Cinema/Ruinscraft. 

The license is also fairly restricting. In general, this project isn't for public use. It's open source mainly so our players can audit the code and make changes if they want to.

**Comment by ItsK1tty** [comment]
Can't people just watch movies together?

**Comment by dextonanderson** [comment]
It requires the server plugin (written in Bukkit), which is not publicly available. It also requires the use of our installer to install the CEF binaries. See https://github.com/Ruinscraft/stevecinema-installer

**Comment by dextonanderson** [comment]
> Can't people just watch movies together?

But yes, you are able to watch movies/youtube videos/etc on the Steve Cinema server with this

**Comment by ItsK1tty** [comment]
Since this PR will be closed anyway, previously you mentioned that you're going to upgrade the webdisplays to support h264 (https://github.com/montoyo/webdisplays/issues/114#issuecomment-864362647). How's the progress?

**Comment by dextonanderson** [comment]
You can use this project to patch MCEF (Ruinscraft fork, 1.31) binaries to support proprietary codecs

https://github.com/Ruinscraft/mcef-codec-patch

I don't have the native binaries compiled. You'll have to have python installed and install the dependencies in requirements.txt, then run `python installer.py`

**Comment by dextonanderson** [comment]
I have some time, i'll go ahead and compiled a release .exe binary for Windows

**Comment by ItsK1tty** [comment]
Oh, don't worry about that, I have them compiled already. Is there any other way to contact you besides creating a PR or an issue?

**Comment by dextonanderson** [comment]
> Oh, don't worry about that, I have them compiled already. Is there any other way to contact you besides creating a PR or an issue?

Oh alright.

My email is andersond@ruinscraft.com, discord is royalkingkb#6223

**Comment by ItsK1tty** [comment]
изображение
K1tty#2077, please

**Pull request closed without merging**
